# Generated by Django 3.1.2 on 2020-11-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircondition',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
