# Generated by Django 3.1.2 on 2020-12-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0002_auto_20201102_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
