# Generated by Django 3.1.2 on 2020-12-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0003_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircondition',
            name='pressure',
            field=models.FloatField(default=90000),
        ),
    ]
