# Generated by Django 3.1.2 on 2020-12-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0004_aircondition_pressure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='status',
            field=models.CharField(blank=True, choices=[('ON', 'ON'), ('OFF', 'OFF'), ('AUTO', 'AUTO')], max_length=5, null=True),
        ),
    ]
