# Generated by Django 3.1.2 on 2020-12-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0005_auto_20201222_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='status',
            field=models.BooleanField(),
        ),
    ]
