# Generated by Django 3.1.2 on 2020-12-22 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0006_auto_20201222_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motor',
            name='max_temp',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='motor',
            name='min_temp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='motor',
            name='start_time',
            field=models.TimeField(default=datetime.time(7, 30)),
        ),
        migrations.AddField(
            model_name='motor',
            name='stop_time',
            field=models.TimeField(default=datetime.time(4, 30)),
        ),
    ]
