# Generated by Django 3.1.2 on 2021-02-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0009_auto_20210128_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('min_temp', models.IntegerField()),
                ('max_temp', models.IntegerField()),
                ('start', models.TimeField()),
                ('stop', models.TimeField()),
                ('status', models.BooleanField()),
                ('auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('temp', models.IntegerField()),
            ],
        ),
    ]
