# Generated by Django 3.1.2 on 2021-02-24 03:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0010_roomget_roompost'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompost',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
