# Generated by Django 3.1.2 on 2021-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0011_roompost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomget',
            name='description',
            field=models.TextField(default='', max_length=50),
        ),
    ]
