# Generated by Django 3.1.2 on 2021-03-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp8266', '0012_roomget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomget',
            name='description',
            field=models.CharField(default='', max_length=50),
        ),
    ]
