# Generated by Django 3.1.2 on 2020-11-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
