# Generated by Django 3.1.2 on 2020-11-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0003_letter_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible', models.CharField(blank=True, max_length=30, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('subject', models.CharField(blank=True, max_length=50, null=True)),
                ('responsible', models.CharField(blank=True, max_length=30, null=True)),
                ('deadline', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
