# Generated by Django 3.1.2 on 2020-11-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('heat_capacity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('consumption', models.IntegerField()),
                ('water_capacity', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('flange_size', models.IntegerField()),
            ],
        ),
    ]
