# Generated by Django 3.1.2 on 2020-11-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_boiler_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stiff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('capacity', models.IntegerField()),
                ('resin', models.IntegerField()),
                ('flow_rate', models.IntegerField()),
                ('backwash_flow_rate', models.IntegerField()),
                ('valve_size', models.CharField(max_length=10)),
                ('tank_size', models.CharField(max_length=10)),
                ('salt_amount', models.CharField(max_length=10)),
                ('card', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
