# Generated by Django 3.1.2 on 2020-11-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_stiff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiff',
            name='resin',
            field=models.FloatField(),
        ),
    ]
