# Generated by Django 3.1.2 on 2020-11-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20201114_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('input', models.CharField(max_length=10)),
                ('output', models.CharField(max_length=10)),
                ('motor_power', models.FloatField()),
                ('motor_speed', models.IntegerField()),
                ('helical_power', models.CharField(max_length=10)),
                ('helical_speed', models.CharField(max_length=10)),
                ('helical_flow_rate', models.CharField(max_length=10)),
                ('helical_height', models.CharField(max_length=10)),
                ('input_valve_size', models.CharField(max_length=10)),
                ('output_valve_size', models.CharField(max_length=10)),
                ('card', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
