# Generated by Django 3.1.2 on 2020-11-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0006_auto_20201118_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='door_material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='isolator_density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='isolator_material',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='isolator_thickness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
