# Generated by Django 3.1.2 on 2020-11-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0007_auto_20201120_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='media/identity/pump'),
        ),
    ]
