# Generated by Django 3.1.2 on 2020-11-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20201123_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomesticHotWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('tank_height', models.IntegerField(blank=True, null=True)),
                ('tank_diameter', models.IntegerField(blank=True, null=True)),
                ('coil_length', models.IntegerField(blank=True, null=True)),
                ('coil_diameter', models.IntegerField(blank=True, null=True)),
                ('coil_surface', models.FloatField(blank=True, null=True)),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/DomesticHotWater')),
            ],
        ),
    ]
