# Generated by Django 3.1.2 on 2020-11-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0009_domestichotwater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiff',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='media/identity/WaterSoftener'),
        ),
    ]
