# Generated by Django 3.1.2 on 2020-11-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0011_repair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
