# Generated by Django 3.1.2 on 2020-12-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0014_auto_20201202_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='repairman',
            field=models.CharField(blank=True, choices=[('محمد یاوری', 'محمد یاوری'), ('اسلامی', 'اسلامی')], max_length=30, null=True),
        ),
    ]
