# Generated by Django 3.1.2 on 2020-12-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0015_auto_20201202_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpTank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('capacity', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('height', models.IntegerField()),
                ('valve_size', models.CharField(max_length=10)),
                ('weight', models.IntegerField(max_length=10)),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/ExpansionTank')),
            ],
        ),
        migrations.AlterField(
            model_name='repair',
            name='device',
            field=models.CharField(choices=[('B001', 'B001'), ('B002', 'B002'), ('B003', 'B003'), ('B004', 'B004'), ('P001', 'P001'), ('P002', 'P002'), ('P003', 'P003'), ('P004', 'P004'), ('P005', 'P005'), ('P006', 'P006'), ('P007', 'P007'), ('P008', 'P008'), ('P009', 'P009'), ('P010', 'P010'), ('P011', 'P011'), ('P012', 'P012'), ('P013', 'P013'), ('P014', 'P014'), ('P015', 'P015'), ('D001', 'D001'), ('D002', 'D002'), ('S001', 'S001')], max_length=30),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repairman',
            field=models.CharField(blank=True, choices=[('محمد یاوری', 'محمد یاوری'), ('محسن اسلامی', 'محسن اسلامی'), ('هاشم صمدی', 'هاشم صمدی')], max_length=30, null=True),
        ),
    ]
