# Generated by Django 3.1.2 on 2020-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0016_auto_20201203_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chiller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('cool_capacity', models.IntegerField()),
                ('cool_water_flow_rate', models.FloatField()),
                ('comp_model', models.CharField(max_length=20)),
                ('comp_power', models.FloatField()),
                ('comp_num', models.IntegerField()),
                ('cond_model', models.CharField(max_length=20)),
                ('cond_flow_rate', models.CharField(max_length=10)),
                ('cond_pressure_drop', models.FloatField()),
                ('cooler_model', models.CharField(max_length=20)),
                ('cooler_pressure_drop', models.FloatField()),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/Chiller')),
            ],
        ),
        migrations.AlterField(
            model_name='exptank',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
