# Generated by Django 3.1.2 on 2020-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0017_auto_20201203_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirConditioner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('motor_quantity', models.IntegerField()),
                ('motor_power', models.FloatField()),
                ('fan_quantity', models.IntegerField()),
                ('fan_speed', models.IntegerField()),
                ('fan_size', models.CharField(max_length=20)),
                ('coil_cool', models.IntegerField()),
                ('coil_warm', models.IntegerField()),
                ('coil_pre_warm', models.IntegerField()),
                ('flow_rate', models.IntegerField()),
                ('TSP', models.FloatField()),
                ('ESP', models.FloatField()),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/Chiller')),
            ],
        ),
    ]
