# Generated by Django 3.1.2 on 2020-12-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0020_auto_20201214_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconditioner',
            name='device',
            field=models.CharField(default='هواساز', max_length=10),
        ),
        migrations.AddField(
            model_name='airconditioner',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='boiler',
            name='device',
            field=models.CharField(default='دیگ', max_length=10),
        ),
        migrations.AddField(
            model_name='boiler',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chiller',
            name='device',
            field=models.CharField(default='چیلر', max_length=10),
        ),
        migrations.AddField(
            model_name='chiller',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='domestichotwater',
            name='device',
            field=models.CharField(default='منبع کویل دار', max_length=10),
        ),
        migrations.AddField(
            model_name='domestichotwater',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exptank',
            name='device',
            field=models.CharField(default='منبع انبساط', max_length=10),
        ),
        migrations.AddField(
            model_name='exptank',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pump',
            name='device',
            field=models.CharField(default='پمپ', max_length=10),
        ),
        migrations.AddField(
            model_name='pump',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stiff',
            name='device',
            field=models.CharField(default='سختی گیر', max_length=10),
        ),
        migrations.AddField(
            model_name='stiff',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='device',
            field=models.CharField(choices=[], max_length=30),
        ),
    ]
