# Generated by Django 3.1.2 on 2020-12-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0022_auto_20201229_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='device',
            field=models.CharField(default='دیگ و مشعل', max_length=10),
        ),
    ]
