# Generated by Django 3.1.2 on 2021-01-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0023_auto_20201229_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='ژنراتور', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('power', models.IntegerField()),
                ('rpm', models.FloatField()),
                ('faze', models.IntegerField()),
                ('frequency', models.IntegerField()),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/Generator')),
            ],
        ),
        migrations.AlterField(
            model_name='airconditioner',
            name='card',
            field=models.ImageField(blank=True, null=True, upload_to='media/identity/AirConditioner'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='device',
            field=models.CharField(choices=[('B001', 'B001'), ('B002', 'B002'), ('B003', 'B003'), ('B004', 'B004'), ('B101', 'B101'), ('B102', 'B102'), ('P001', 'P001'), ('P002', 'P002'), ('P003', 'P003'), ('P004', 'P004'), ('P005', 'P005'), ('P006', 'P006'), ('P007', 'P007'), ('P008', 'P008'), ('P009', 'P009'), ('P010', 'P010'), ('P011', 'P011'), ('P012', 'P012'), ('P013', 'P013'), ('P014', 'P014'), ('P015', 'P015'), ('P101', 'P101'), ('P102', 'P102'), ('P103', 'P103'), ('D001', 'D001'), ('D002', 'D002'), ('D101', 'D101'), ('D102', 'D102'), ('S001', 'S001'), ('E001', 'E001'), ('E002', 'E002'), ('E101', 'E101'), ('CH001', 'CH001'), ('CH002', 'CH002'), ('CH003', 'CH003'), ('A001', 'A001'), ('A002', 'A002'), ('A003', 'A003'), ('A004', 'A004'), ('A005', 'A005'), ('A006', 'A006'), ('A007', 'A007'), ('A008', 'A008'), ('A009-1', 'A009-1'), ('A009-2', 'A009-2')], max_length=30),
        ),
    ]
