# Generated by Django 3.1.2 on 2021-02-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0025_auto_20210203_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpLinear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='پمپ خطی', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('input', models.CharField(max_length=10)),
                ('output', models.CharField(max_length=10)),
                ('motor_power', models.FloatField()),
                ('motor_speed', models.IntegerField()),
                ('input_valve_size', models.CharField(max_length=10)),
                ('output_valve_size', models.CharField(max_length=10)),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/pumplinear')),
            ],
        ),
    ]
