# Generated by Django 3.1.2 on 2021-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0027_auto_20210213_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoolingTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(default='برج خنک کن', max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('_type', models.CharField(max_length=30)),
                ('serial', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('since', models.CharField(max_length=4)),
                ('motor_power', models.IntegerField()),
                ('motor_speed', models.IntegerField()),
                ('fan', models.CharField(max_length=20)),
                ('built', models.CharField(max_length=20)),
                ('flow', models.FloatField()),
                ('temp_input', models.IntegerField()),
                ('temp_output', models.IntegerField()),
                ('card', models.ImageField(blank=True, null=True, upload_to='media/identity/CoolingTower')),
            ],
        ),
    ]
