# Generated by Django 3.1.2 on 2020-12-19 23:26

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ')),
                ('season', models.CharField(max_length=10, null=True, verbose_name='فصل')),
                ('duration', models.CharField(choices=[('1', 'روزانه'), ('2', 'هفتگی'), ('3', 'ماهانه'), ('4', 'سالانه')], max_length=10, verbose_name='مدت')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name_plural': 'چک لیست ها',
            },
        ),
        migrations.CreateModel(
            name='Checklists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=10, verbose_name='تجهیز')),
                ('code', models.CharField(max_length=10, verbose_name='کد تجهیز')),
                ('location', models.CharField(max_length=20, verbose_name='موقعیت')),
                ('duty', models.TextField(max_length=100, verbose_name='ملاحظات')),
                ('factor', models.IntegerField(verbose_name='ضریب')),
                ('status', models.BooleanField(verbose_name='وضعیت')),
                ('explain', models.TextField(max_length=100, verbose_name='توضیحات')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmplan.checklist')),
            ],
        ),
    ]
