# Generated by Django 3.1.2 on 2020-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='season',
            field=models.CharField(choices=[('1', 'زمستان'), ('2', 'تابستان'), ('3', 'چهارفصل')], max_length=10, verbose_name='فصل'),
        ),
    ]
