# Generated by Django 3.1.2 on 2020-12-20 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmplan', '0002_auto_20201220_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name_plural': 'چک لیست'},
        ),
        migrations.AlterModelOptions(
            name='checklists',
            options={'verbose_name_plural': 'چک لیست ها'},
        ),
    ]
