# Generated by Django 3.1.2 on 2020-12-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmplan', '0004_auto_20201220_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='status',
            field=models.NullBooleanField(verbose_name='وضعیت'),
        ),
    ]
