# Generated by Django 3.1.2 on 2020-12-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmplan', '0005_auto_20201220_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='status',
            field=models.CharField(choices=[('1', 'خوب'), ('2', 'بد')], max_length=10, verbose_name='وضعیت'),
        ),
    ]
