# Generated by Django 3.1.2 on 2020-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmplan', '0009_auto_20201220_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklists',
            name='status',
            field=models.BooleanField(blank=True, max_length=10, null=True, verbose_name='وضعیت'),
        ),
    ]
